dbt_gp:
  outputs:
    dev:
      catalog: dbt_tut_dev
      host: dbc-7b023fdf-61a6.cloud.databricks.com
      http_path: /sql/1.0/warehouses/9ab31a53bd8b23c4
      schema: default
      threads: 1
      token: xyz
      type: databricks
    prod:
      catalog: dbt_tut_prod
      host: dbc-7b023fdf-61a6.cloud.databricks.com
      http_path: /sql/1.0/warehouses/9ab31a53bd8b23c4
      schema: default
      threads: 1
      token: xyz
      type: databricks
  target: dev
    
